### Google만 email, name 추가
POST {{blog_api}}/api/v1/auth
Content-Type: application/json

{
  "email": "tnswh2023@gmail.com",
  "name": "유순조",
  "accessToken": "4/0AX4XfWguyykSI2JXzAFb54eqaZyYDvOemqBilyFxIP3Mgcz6-pVSEoKMpslHjSwN_hxmsg",
  "provider": "GOOGLE"
}

### facebook access_token 얻기

GET https://graph.facebook.com/v13.0/oauth/access_token?code={{CODE}}&client_id={{CLIENT_ID}}&client_secret={{CLIENT_SECRET}}&redirect_uri=https://api.nalbang.debug.one/api/v1/code

### facebook
POST {{blog_api}}/api/v1/auth
Content-Type: application/json

{
  "accessToken": "EAAGFLpc2EBoBAEx212pnWiPqzjfkfeD02tVcQAxamxPZC2OZCYmIXXSbhUTxcu1w8LGzXt1q7KjkYIl1ZAqsjZBxb99hNeNnSZB2xdLtypaHVMM8i1BX3gWZChsRliCr1vtfstQ2lfZBiWKZBZB6xbGQBuOxqD1W8cXKr4Nmu8bNDXFyHOxJI5UGJ3jplUbNiW05CWGHJ28yTTtI2JC62khDus65bVD0rCav1LRvSheab3QZDZD",
  "provider": "FACEBOOK"
}