### 게시글 리스트
GET {{blog_api}}/api/v1/board/list?size=5&page=1&hashTagList=생일,기념

### 게시글 좋아요
POST {{blog_api}}/api/v1/board/like
Content-Type: application/json
Authorization: {{MEMBER}}

{
  "boardId": 1
}

### 게시글 좋아요 취소
DELETE {{blog_api}}/api/v1/board/like
Content-Type: application/json
Authorization: {{MEMBER}}

{
  "boardId": 1
}

### 해쉬태그 리스트 (중복 제외)
GET {{blog_api}}/api/v1/hashTag
Content-Type: application/json