FROM adoptopenjdk/openjdk11

WORKDIR /usr/blog/app

COPY ./ ./

RUN chmod +x gradlew
RUN ./gradlew clean bootJar

EXPOSE 9000

ENTRYPOINT ["java", "-jar", "/usr/blog/app/blog-admin/build/libs/blog-admin-0.0.1-BLOG.jar", "--spring.profiles.active=local"]


