version: "3"
services:
  api:
    container_name: blog_api
    build:
      context: .
      dockerfile: Dockerfile_api
    networks:
      - blog-network
    ports:
      - "8080:8080"
  admin:
    container_name: blog_admin
    build:
      context: .
      dockerfile: Dockerfile_admin
    networks:
      - blog-network
    ports:
      - "9000:9000"
networks:
  blog-network: