spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mariadb://velog.cqa7rhjwuoqr.ap-northeast-2.rds.amazonaws.com/blog_dev
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update