management:
  trace:
    http:
      enabled: true
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8080
  shutdown: graceful

spring:
  boot:
    admin:
      client:
        auto-registration: true
        url: https://api-manage-lovga.site
        username: tnswh2023
        password: 1234
        instance:
          name: blog
          metadata:
            user.name: tnswh2023
            user.password: 1234
          service-url: https://api-lovga.site
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  jpa:
    open-in-view: false
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        format_sql: true

logging:
  level:
    root: INFO
    org:
      springframework: INFO
      hibernate:
        type:
          descriptor:
            sql: trace

cloud:
  aws:
    s3:
      bucket: potato-velog-sunjo
    region:
      static: ap-northeast-2
    stack:
      auto: false

elasticsearch:
  host: https://search-blog-search-6x645wgniksroxemjkwtsurwju.ap-northeast-2.es.amazonaws.com
  port: 9200

---
spring:
  profiles:
    active: local, dev
    include:
      - aws
      - sentry
      - google
      - fb

---
spring:
  profiles:
    active: dev
    include:
      - rds
