POST {{host_api}}/api/v1/board
Content-Type: application/json
Authorization: {{ADMIN}}

{
  "title": "title",
  "content": "content",
  "isPrivate": false,
  "boardThumbnailUrl": "https://naver.com",
  "categoryId": 1
}

### 수정
PUT {{host_api}}/api/v1/board
Content-Type: application/json
Authorization: {{ADMIN}}

{
  "id": 1,
  "title": "title",
  "content": "content",
  "isPrivate": false,
  "boardThumbnailUrl": "https://naver.com",
  "categoryId": 1
}

### 상세보기
GET {{host_api}}/api/v1/board/1
Content-Type: application/json
Authorization: {{ADMIN}}

### 리스트
GET {{host_api}}/api/v1/board/list?page=1&size=1
Authorization: {{ADMIN}}