# 게시글 생성
POST {{blog_admin}}/api/v1/board
Content-Type: application/json
Authorization: {{ADMIN}}

{
  "title": "title",
  "content": "content",
  "isPrivate": false,
  "boardThumbnailUrl": "https://naver.com",
  "categoryId": 1,
  "hashTagList": ["gogo"]
}

### 수정
PUT {{blog_admin}}/api/v1/board
Content-Type: application/json
Authorization: {{ADMIN}}

{
  "id": 1,
  "title": "title",
  "content": "content",
  "isPrivate": false,
  "boardThumbnailUrl": "https://naver.com",
  "categoryId": 1,
  "hashTagList": ["gogo", "자바", "코틀린"]
}

### 상세보기
GET {{blog_admin}}/api/v1/board/1
Content-Type: application/json
Authorization: {{ADMIN}}

### 리스트
GET {{blog_admin}}/api/v1/board/list?page=1&size=1&search=t&category=코코틀린
Authorization: {{ADMIN}}