POST {{blog_admin}}/api/v1/admin/category
Content-Type: application/json
Authorization: {{ADMIN}}

{
  "categoryName": "코코틀린"
}

###
PUT {{blog_admin}}/api/v1/admin/category
Content-Type: application/json
Authorization: {{ADMIN}}

{
  "id": 1,
  "categoryName": "코틀린"
}

###
GET {{blog_admin}}/api/v1/admin/category/list
Content-Type: application/json
Authorization: {{ADMIN}}
