POST {{blog_admin}}/api/v1/admin/member/signup
Content-Type: application/json

{
  "email": "tnswh2023@naver.com",
  "password": "1234"
}

###
POST {{blog_admin}}/api/v1/admin/member/login
Content-Type: application/json

{
  "email": "tnswh2023@naver.com",
  "password": "1234"
}
> {%
client.global.set('ADMIN', response.body.data)
client.log(client.global.get('ADMIN'));
 %}

###
GET {{blog_admin}}/api/v1/admin/member
Authorization: {{ADMIN}}
