server:
  port: 9000
  shutdown: graceful

spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 20MB
  jpa:
    open-in-view: false
    properties:
      hibernate:
        default_batch_fetch_size: 1000

logging:
  level:
    root: INFO

cloud:
  aws:
    s3:
      bucket: potato-velog-sunjo
      cloud_front_url: https://d10mjr19pnf1jr.cloudfront.net
    region:
      static: ap-northeast-2
    stack:
      auto: false

---
spring:
  profiles:
    active: local, dev
    include:
      - aws
      - sentry

---
spring:
  profiles:
    active: dev
    include:
      - rds