management:
  trace:
    http:
      enabled: true
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"


server:
  port: 9000
  shutdown: graceful

spring:
  boot:
    admin:
      client:
        auto-registration: true
        url: https://api-manage-lovga.site
        username: tnswh2023
        password: 1234
        instance:
          name: blog
          metadata:
            user.name: tnswh2023
            user.password: 1234
          service-url: http://localhost:9000
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 20MB
  jpa:
    open-in-view: false
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        format_sql: true

logging:
  level:
    root: INFO
    org:
      springframework: INFO
      hibernate:
        type:
          descriptor:
            sql: trace

cloud:
  aws:
    s3:
      bucket: potato-velog-sunjo
      cloud_front_url: https://d10mjr19pnf1jr.cloudfront.net
    region:
      static: ap-northeast-2
    stack:
      auto: false

elasticsearch:
  host: localhost
  port: 9200
  indecies:
    testIndexName: test

---
spring:
  profiles:
    active: local
    include:
      - aws
      - sentry

---
spring:
  profiles:
    active: dev
    include:
      - rds
      - aws
      - sentry