server:
  port: 9000

spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

logging:
  level:
    root: INFO

cloud:
  aws:
    s3:
      bucket: potato-velog-sunjo
    region:
      static: ap-northeast-2
    stack:
      auto: false

---
spring:
  profiles:
    active: local, dev
    include:
      - aws
      - sentry

---
spring:
  profiles:
    active: dev
    include:
      - rds