spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://my8002.gabiadb.com:3306
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    hibernate:
      ddl-auto: update
