name: velog docker cd

on:
  push:
    branches:
      - docker
env:
  DOCKER_IMAGE: ghcr.io/yusunjo/blog
  VERSION: ${{ github.sha }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create aws-key.yml file
        env:
          CLOUD_AWS_CREDENTIALS_ACCESS_KEY: ${{ secrets.CLOUD_AWS_CREDENTIALS_ACCESS_KEY }}
          CLOUD_AWS_CREDENTIALS_SECRET_KEY: ${{ secrets.CLOUD_AWS_CREDENTIALS_SECRET_KEY }}
          RESOURCE_FILE: blog-admin/src/main/resources/aws-key.yml
        run: |
          touch $RESOURCE_FILE
          echo "cloud.aws.credentials.access_key: $CLOUD_AWS_CREDENTIALS_ACCESS_KEY \
                cloud.aws.credentials.secret_key: $CLOUD_AWS_CREDENTIALS_SECRET_KEY" >> $RESOURCE_FILE

      - name: Create aws-key.yml file
        env:
          CLOUD_AWS_CREDENTIALS_ACCESS_KEY: ${{ secrets.CLOUD_AWS_CREDENTIALS_ACCESS_KEY }}
          CLOUD_AWS_CREDENTIALS_SECRET_KEY: ${{ secrets.CLOUD_AWS_CREDENTIALS_SECRET_KEY }}
          RESOURCE_FILE: blog-api/src/main/resources/aws-key.yml
        run: |
          touch $RESOURCE_FILE
          echo "cloud.aws.credentials.access_key: $CLOUD_AWS_CREDENTIALS_ACCESS_KEY \
                cloud.aws.credentials.secret_key: $CLOUD_AWS_CREDENTIALS_SECRET_KEY" >> $RESOURCE_FILE

      - name: Login to ghcr
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: docker image build and push
        run: |
          docker build -t $DOCKER_IMAGE:$VERSION .
          docker tag $DOCKER_IMAGE:$VERSION $DOCKER_IMAGE:latest
          docker push $DOCKER_IMAGE:$VERSION
          docker push $DOCKER_IMAGE:latest
          echo -e "${{ secrets.CR_PAT }}" > deploy/GIT-TOKEN.txt
          cat deploy/GIT-TOKEN.txt